config/routes.rb
Rails.application.routes.draw do
  
  devise_for :workers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :worker do 
    root to: 'devise/sessions#new'
  end

  resources :workers do 
    member do 
      get :reset_password
      put :change_current_city
    end
  end
  resources :roles

  resources :categories do 
    resources :products
     member do
      get :prices
      post :init_prices
    end
  end

  resources :prices

  resources :price_rules

  resources :stations do
  end

  resources :addresses do
    collection do
      get :suggestion
    end
  end

  resources :cities

  resources :couriers

  resources :orders do 
  end

  resources :users do 
    resources :user_cards do 
      member do 
        get :charge
        post :charge
      end
    end
    resources :coupons
  end

  resources :coupons
  resources :coupon_lists do 
    resources :order_promotions, only: [:new, :create, :edit, :update, :destroy]
  end  

  resources :user_card_charge_settings

  post '/categories/:id', :to => 'categories#recovery'
  post '/categories/:category_id/products/:id', :to => 'products#recovery'

  mount ActionCable.server => '/cable'

  root to: 'stations#index'
end

app/models/user_card_charge_setting.rb
class UserCardChargeSetting < ApplicationRecord
end

app/controllers/user_card_charge_settings_controller.rb
class UserCardChargeSettingsController < ApplicationController
  before_action :set_user_card_charge_setting, only: [:show, :edit, :update, :destroy]

  # GET /user_card_charge_settings
  # GET /user_card_charge_settings.json
  def index
    @user_card_charge_settings = UserCardChargeSetting.paginate(page: params[:page], per_page: 10).order(updated_at: :desc)
  end

  # GET /user_card_charge_settings/1
  # GET /user_card_charge_settings/1.json
  def show
  end

  # GET /user_card_charge_settings/new
  def new
    @user_card_charge_setting = UserCardChargeSetting.new
  end

  # GET /user_card_charge_settings/1/edit
  def edit
  end

  # POST /user_card_charge_settings
  # POST /user_card_charge_settings.json
  def create
    @user_card_charge_setting = UserCardChargeSetting.new(user_card_charge_setting_params)

    respond_to do |format|
      if @user_card_charge_setting.save
        format.html { redirect_to user_card_charge_settings_url, notice: 'User card charge setting was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /user_card_charge_settings/1
  # PATCH/PUT /user_card_charge_settings/1.json
  def update
    respond_to do |format|
      if @user_card_charge_setting.update(user_card_charge_setting_params)
        format.html { redirect_to user_card_charge_settings_url, notice: 'User card charge setting was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /user_card_charge_settings/1
  # DELETE /user_card_charge_settings/1.json
  def destroy
    @user_card_charge_setting.destroy
    respond_to do |format|
      format.html { redirect_to user_card_charge_settings_url, notice: 'User card charge setting was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_card_charge_setting
      @user_card_charge_setting = UserCardChargeSetting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_card_charge_setting_params
      params.require(:user_card_charge_setting).permit(:min, :money_give)
    end
end

app/views/user_card_charge_settings/_form.html.slim
= simple_form_for(@user_card_charge_setting) do |f|
  = f.error_notification

  .form-inputs
    = f.input :min
    = f.input :money_give

  .form-actions
    = f.button :submit

app/views/user_card_charge_settings/edit.html.slim
h1 Editing user_card_charge_setting

== render 'form'

= link_to 'Show', @user_card_charge_setting
'|
= link_to 'Back', user_card_charge_settings_path

app/views/user_card_charge_settings/index.html.slim
.panel.panel-default
  .panel-heading
    | 充值优惠
  .panel-body
    table.table.table-striped
      thead
        tr
          th Min
          th Money give
          th
          th

      tbody
        - @user_card_charge_settings.each do |user_card_charge_setting|
          tr
            td = user_card_charge_setting.min
            td = user_card_charge_setting.money_give
            td = link_to 'Edit', edit_user_card_charge_setting_path(user_card_charge_setting)
            td = link_to 'Destroy', user_card_charge_setting, data: { confirm: 'Are you sure?' }, method: :delete
    = will_paginate @user_card_charge_settings, renderer: BootstrapPagination::Rails
  .panel-footer
    = link_to '新建', new_user_card_charge_setting_path, class: 'btn btn-info btn-sm'

app/views/user_card_charge_settings/new.html.slim
h1 New user_card_charge_setting

== render 'form'

= link_to 'Back', user_card_charge_settings_path