config/routes.rb
Rails.application.routes.draw do
  
  devise_for :workers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :worker do 
    root to: 'devise/sessions#new'
  end

  resources :workers do 
    member do 
      get :reset_password
      put :change_current_city
    end
  end
  resources :roles

  resources :categories do 
    resources :products
     member do
      get :prices
      post :init_prices
    end
  end

  resources :prices

  resources :price_rules

  resources :stations do
  end

  resources :addresses do
    collection do
      get :suggestion
    end
  end

  resources :cities

  resources :couriers

  resources :orders do 
  end

  resources :users do 
    resources :user_cards do 
      member do 
        get :charge
        post :charge
      end
    end
    resources :coupons
  end

  resources :coupons
  resources :coupon_lists do 
    resources :order_promotions, only: [:new, :create, :edit, :update, :destroy]
  end  

  resources :user_card_charge_settings

  post '/categories/:id', :to => 'categories#recovery'
  post '/categories/:category_id/products/:id', :to => 'products#recovery'

  mount ActionCable.server => '/cable'

  root to: 'stations#index'
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products

	has_many :prices, through: :products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
  
  before_action :set_category, only: [:show, :edit, :update, :destroy, :prices, :init_prices]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.paginate(page: params[:page], per_page: 10).order(updated_at: :desc)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @products = @category.products.paginate(page: params[:page], per_page: 10).order(updated_at: :desc)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    params = category_params
    if params['logo']
      filename = generate_filename
      Image.upload(params['logo'].tempfile.path, filename)
      params['logo'] = filename
    end
    @category = Category.new(params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    params = category_params
    if params['logo']
      filename = generate_filename
      Image.upload(params['logo'].tempfile.path, filename)
      params['logo'] = filename
    end
    
    respond_to do |format|
      if @category.update(params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    # 标记删除品类，并对该品类下的产品标记已删除
    @category.update_attribute(:is_del, true)

    # 若该品类下存在产品则进行以下操作
    if @category.products
      @category.products.each do |product|
        product.update_attribute(:is_del, true)
      end
    end
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # RECOVERY /categories/1
  # RECOVERY /categories/1.json
  def recovery   
    # 标记恢复品类，并对该品类下的所有产品标记已恢复
    @category.update_attribute(:is_del, false) 

    # 若该品类下存在产品则进行以下操作
    if @category.products
      @category.products.each do |product|
        product.update_attribute(:is_del, false)
      end
    end

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully recoveryed.' }
      format.json { head :no_content }
    end
  end

  def prices
    @prices = @category.prices.paginate(page: params[:page], per_page: 10)
  end

  def init_prices
    @category.products.each do |product|
      product.create_price unless product.price
    end
    redirect_to prices_category_path(@category)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :logo, :is_del)
    end

    def generate_filename
      "category-#{Time.now.to_i * 1000 + rand(1000)}"
    end
  end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.slim
= simple_form_for(@category) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :logo, as: :file

  .form-actions
    = f.button :submit

app/views/categories/edit.html.slim
h1 Editing category

== render 'form'

=> link_to 'Show', @category
'|
=< link_to 'Back', categories_path

app/views/categories/index.html.slim
.panel.panel-default
  .panel-heading
    | 品类
  .panel-body
    table.table.table-striped
      thead
        tr
          th Name
          th Logo
          th Is del
          th
          th
          th

      tbody
        - @categories.each do |category|
          tr
            td = category.name
            td = image_tag qiniu_url(category.logo), size: '150x150'
            td
              - if category.is_del
                  span.label.label-primary 是
              - else
                  span.label.label-default 否
            td = link_to 'Show', category
            td = link_to 'Edit', edit_category_path(category)
            td
              - if !category.is_del
                  = link_to 'Destroy', category, data: { confirm: 'Are you sure to destroy?' }, method: :delete
              - else
                  = link_to 'Recovery', category, data: { confirm: 'Are you sure to recovery?' }, method: :recovery

    = will_paginate @categories, renderer: BootstrapPagination::Rails
  .panel-footer
    = link_to 'New Category', new_category_path, class: 'btn btn-info btn-sm'

app/views/categories/new.html.slim
h1 New category

== render 'form'

= link_to 'Back', categories_path

app/views/categories/prices.html.slim
.panel.panel-default
  .panel-heading
    | 价格表
  .panel-body
    table.table.table-striped
      thead
        tr
          th 商品
          th width='10%' A
          th width='10%' B
          th width='10%' C
          th width='10%' D
          th width='10%' E
          th width='10%' F

      tbody
        - @prices.each do |price|
          tr
            td = price.product.name
            - 1.upto(6).each do |i|
              td 
                span.editable data={type: :text, name: "price[price#{i}]", 'url' => price_path(price)}
                  = price.send("price#{i}")
    = will_paginate @prices, renderer: BootstrapPagination::Rails
  .panel-footer
    = link_to '初始化', init_prices_category_path(@category), class: 'btn btn-info btn-sm', method: :post

javascript:
  // 设置为空时的填充文字
  $('.editable').editable({
    emptytext: '-'
  });
  // 当弹出输入框时去掉输入框中的'-'
  $('.editable').on('shown', function(e, editable) {
    setTimeout(function() {
      $('.editable-input>input').focus();
      $('.editable-input>input').select();
    }, 0);
  });

app/views/categories/show.html.slim
ol.breadcrumb
  li.active 
    = link_to '品类', categories_path
  li
    = @category.name

.clear
br

table.table.table-striped.no-border
  tr
    td width='25%' Logo
    td width='25%' = image_tag qiniu_url(@category.logo), size: '150x150'
    td width='25%' Is del
    td width='25%' 
      - if @category.is_del
        span.label.label-primary 是
      - else
        span.label.label-default 否



.panel.panel-default
  .panel-heading#service_categories
    | 商品
  .panel-body
    table.table.table-striped
      thead
        tr
          th width='25%' Name
          th width='10%' Logo
          th width='10%' is_del
          th width='5%' 
          th width='5%'
      tbody
        = render @products
    = will_paginate @products, renderer: BootstrapPagination::Rails
  .panel-footer
    = link_to '新建商品', new_category_product_path(@category), class: 'btn btn-info btn-sm'